"""empty message

Revision ID: 60d32e4a1cbb
Revises: fe94c8028f5f
Create Date: 2018-05-21 01:56:12.364213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d32e4a1cbb'
down_revision = 'fe94c8028f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('job_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'job_rate')
    # ### end Alembic commands ###
