"""empty message

Revision ID: af9cac3809bb
Revises: e7a999d9e4f9
Create Date: 2018-07-18 16:21:10.336786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9cac3809bb'
down_revision = 'e7a999d9e4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table', sa.Integer(), nullable=True),
    sa.Column('pn', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=15), nullable=True),
    sa.Column('rework', sa.Boolean(), nullable=True),
    sa.Column('nit', sa.Integer(), nullable=True),
    sa.Column('total_pcs', sa.Integer(), nullable=True),
    sa.Column('good_pcs', sa.Integer(), nullable=True),
    sa.Column('scrap_pcs', sa.Integer(), nullable=True),
    sa.Column('user_modified_after_submission', sa.Boolean(), nullable=True),
    sa.Column('real_time_scans', sa.Boolean(), nullable=True),
    sa.Column('last_submit_time', sa.DateTime(), nullable=True),
    sa.Column('job_start_time', sa.DateTime(), nullable=True),
    sa.Column('job_end_time', sa.DateTime(), nullable=True),
    sa.Column('job_elapsed_time', sa.String(length=64), nullable=True),
    sa.Column('job_rate', sa.Integer(), nullable=True),
    sa.Column('job_number_of_scans', sa.Integer(), nullable=True),
    sa.Column('lunch_break_taken', sa.Boolean(), nullable=True),
    sa.Column('lunch_break_start_time', sa.DateTime(), nullable=True),
    sa.Column('lunch_break_end_time', sa.DateTime(), nullable=True),
    sa.Column('lunch_break_counter', sa.Integer(), nullable=True),
    sa.Column('lunch_break_total_time', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=64), nullable=True),
    sa.Column('Scrap_blisters', sa.Integer(), nullable=True),
    sa.Column('Scrap_plating', sa.Integer(), nullable=True),
    sa.Column('Scrap_flash', sa.Integer(), nullable=True),
    sa.Column('Scrap_assembly_issues', sa.Integer(), nullable=True),
    sa.Column('Scrap_auto_sort', sa.Integer(), nullable=True),
    sa.Column('Scrap_bad_threads', sa.Integer(), nullable=True),
    sa.Column('Scrap_bent', sa.Integer(), nullable=True),
    sa.Column('Scrap_broken_or_damaged_core', sa.Integer(), nullable=True),
    sa.Column('Scrap_buffing', sa.Integer(), nullable=True),
    sa.Column('Scrap_contamination', sa.Integer(), nullable=True),
    sa.Column('Scrap_damaged_die', sa.Integer(), nullable=True),
    sa.Column('Scrap_debris_stuck_in_part', sa.Integer(), nullable=True),
    sa.Column('Scrap_dimensional', sa.Integer(), nullable=True),
    sa.Column('Scrap_gate_vestige', sa.Integer(), nullable=True),
    sa.Column('Scrap_heat_sinks', sa.Integer(), nullable=True),
    sa.Column('Scrap_high_or_low_ejectors', sa.Integer(), nullable=True),
    sa.Column('Scrap_lamination', sa.Integer(), nullable=True),
    sa.Column('Scrap_leak_test_failed', sa.Integer(), nullable=True),
    sa.Column('Scrap_mixed_parts', sa.Integer(), nullable=True),
    sa.Column('Scrap_other', sa.Integer(), nullable=True),
    sa.Column('Scrap_part_damage', sa.Integer(), nullable=True),
    sa.Column('Scrap_parts_not_tapped', sa.Integer(), nullable=True),
    sa.Column('Scrap_parts_on_gates', sa.Integer(), nullable=True),
    sa.Column('Scrap_poor_fill', sa.Integer(), nullable=True),
    sa.Column('Scrap_porosity', sa.Integer(), nullable=True),
    sa.Column('Scrap_skiving', sa.Integer(), nullable=True),
    sa.Column('Scrap_soldering_and_dragging', sa.Integer(), nullable=True),
    sa.Column('Scrap_start_up_scrap', sa.Integer(), nullable=True),
    sa.Column('Scrap_surface_finish', sa.Integer(), nullable=True),
    sa.Column('Scrap_trim_damage', sa.Integer(), nullable=True),
    sa.Column('Scrap_weight_out_of_specification', sa.Integer(), nullable=True),
    sa.Column('Scrap_wrong_part', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
