"""empty message

Revision ID: de9920b06c7b
Revises: f3083f7f52b8
Create Date: 2018-05-06 20:52:35.808297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de9920b06c7b'
down_revision = 'f3083f7f52b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('Scrap_flash', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'Scrap_flash')
    # ### end Alembic commands ###
