"""DB

Revision ID: f3083f7f52b8
Revises: 
Create Date: 2018-04-28 15:54:32.640862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3083f7f52b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('temppassword', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table', sa.Integer(), nullable=True),
    sa.Column('pn', sa.Integer(), nullable=True),
    sa.Column('job', sa.Integer(), nullable=True),
    sa.Column('operation', sa.Integer(), nullable=True),
    sa.Column('rework', sa.Boolean(), nullable=True),
    sa.Column('nit', sa.Integer(), nullable=True),
    sa.Column('total_pcs', sa.Integer(), nullable=True),
    sa.Column('good_pcs', sa.Integer(), nullable=True),
    sa.Column('scrap_pcs', sa.Integer(), nullable=True),
    sa.Column('Scrap_blisters', sa.Integer(), nullable=True),
    sa.Column('Scrap_plating', sa.Integer(), nullable=True),
    sa.Column('user_modified_after_submission', sa.Boolean(), nullable=True),
    sa.Column('job_start_time', sa.DateTime(), nullable=True),
    sa.Column('job_end_time', sa.DateTime(), nullable=True),
    sa.Column('lunch_taken', sa.Boolean(), nullable=True),
    sa.Column('lunch_start_time', sa.DateTime(), nullable=True),
    sa.Column('lunch_end_time', sa.DateTime(), nullable=True),
    sa.Column('break_taken', sa.Boolean(), nullable=True),
    sa.Column('break_start_time', sa.DateTime(), nullable=True),
    sa.Column('break_end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
